version: "3"
services:
  react-app:
    image: react-typescript
    build: ./
    stdin_open: true
    ports: 
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules